### ISSUE TITLE
Loading completion fails if database is closed

### ISSUE THREAD

**Issue by peterablehmann** [MarkusFreitag/keepassxc-go#13] opened 2023-08-10 17:42 UTC
Loading comletions for zsh using `keepassxc-go completion zsh` fails if the database is closed.
#### Output:
```
Usage:
  keepassxc-go completion zsh [flags]

Flags:
  -h, --help              help for zsh
      --no-descriptions   disable completion descriptions

Global Flags:
  -p, --profile string   Only necessary if keystore contains multiple profiles

1 Datenbank nicht geöffnet
```

This is a problem when loading the completion at shell startup as it produces ugly output before the prompt and does not work.
Is it necessary to query the database when loading completions? What features does it provide? Can it be turned off?

Thanks.

**Comment by MarkusFreitag** [comment] 2023-08-10 18:32
Thanks for reporting this issue.
Honestly that happens by mistake because I've not been aware that the `rootCmd.PersistentPreRun` is also executed for the `completion` commands. I will take a look into that tomorrow, how it can be avoided.

**Comment by MarkusFreitag** [comment] 2023-08-11 15:42
The issue is fixed in the latest [release](https://github.com/MarkusFreitag/keepassxc-go/releases/tag/v1.5.1). Have a nice weekend.

**Closed by MarkusFreitag** 2023-08-11 15:42 UTC
